[tool.ruff]
    fix = true
    fix-only = true
    target-version = "py38"

[tool.ruff.format]
    # Enable reformatting of code snippets in docstrings.
    docstring-code-format = true
    # Format all docstring code snippets with a line length of 60.
    docstring-code-line-length = 60
    # Use `\n` line endings for all files
    line-ending = "lf"
    # Prefer single quotes over double quotes.
    quote-style = "single"
    skip-magic-trailing-comma = true

[tool.ruff.lint]
    # On top of the default `select` (`E4`, E7`, `E9`, and `F`), enable flake8-bugbear (`B`) and flake8-quotes (`Q`).
    extend-select = [
        "C4",
        "F",
        "I",
        "PD",
        "PERF",
        "PIE",
        "PYI",
        "R",
        "RET",
        "SIM",
        "TCH",
        "TID",
    ]
    fixable = ["F"]
[tool.ruff.lint.isort]
    case-sensitive = true
    combine-as-imports = true
    force-single-line = true
    force-wrap-aliases = true
    from-first = true
    order-by-type = true
